const NavigationRoute = {
  splash: 'Splash',
  onBoarding: 'OnBoarding',
  loginSelection: 'LoginSelection',
  login: 'Login',
  register: 'Register',
  registerSuccess: 'RegisterSuccess',
  forgetPassword: 'ForgetPassword',
  otp: 'Otp',
  changePassword: 'ChangePassword',
  finishSetup: 'FinishSetup',
  addContact: 'AddContact',
  home: 'Home',
  bottomTabNavigation: 'BottomTabNavigation',
  profile: 'Profile',
  editProfile: 'EditProfile',
  settings: 'Settings',
  video: 'Video',
  audio: 'Audio',
  write: 'Write',
  writeDetail: 'WriteDetail',
  writeAddMessage: 'writeAddMessage',
  writeEditMessage: 'WriteEditMessage',
  writeAddMember: 'WriteAddMember',
  recipients: 'Recipients',
  verifier: 'Verifier',
  addRecording: 'AddRecording',
  audioAddMember: 'AudioAddMember',
  audioDetail: 'AudioDetail',
  audioEditRecording: 'audioEditRecording',
  addVideoRecording: "AddVideoRecording",
  videoDetail: "VideoDetail",
  videoPlayer: "VideoPlayer"
};

export default NavigationRoute;
